version: "3"

services:
    web-ui:
        build: .
        container_name: "dentalia-profile-node-back"
        restart: "always"
        ports:
            - "9001:9001"
        volumes:
            - "./dist/:/usr/src/app"