version: "3"

services:
    web-ui:
        build: .
        container_name: "dentalia-profile-node-back"
        restart: "always"
        ports:
            - "9001:80"
        volumes:
            - "./dist/:/usr/share/nginx/html"